
/*-----------------------------------------------------------------------------
 *
 *  This file is part of "Tennis game", which is based on Irrlicht Engine.
 *
 *  Revise History:
 *    Date          Author           Comment
 *    2008-08-10    Hu, weixiong     Initial version.
 *    2008-08-16    Hu, weixiong     Added support for string configuration.
 *
 *  Copyright (c) 2007 Intel Corporation.
 *
 *-----------------------------------------------------------------------------
 */

#ifndef _TEST_SCENE_CFG_H_
#define _TEST_SCENE_CFG_H_

#include "utility/GameCfg.h"
#include <dimension2d.h>

using irr::core::dimension2di;
using GameUtility::IResetCfgVars;

extern const dimension2di RENDER_SIZE;
#ifdef WIN32
extern const irr::core::dimension2di SCREEN_RESOLUTION;
#endif

class CTennisCfgVars: public IResetCfgVars
{
public:
	virtual bool saveToFile() const { return true; }
	virtual void ResetCfgVars( ConfigParser& cfg_parser );
};

typedef const char* const CONSTCFGTYPE;

extern const dimension2di RENDER_SIZE;

//keywords
extern CONSTCFGTYPE CFG_FILE_PATH;
extern CONSTCFGTYPE MIN_X_TABLE;
extern CONSTCFGTYPE MIN_Y_TABLE;
extern CONSTCFGTYPE MIN_Z_TABLE;
extern CONSTCFGTYPE MAX_X_TABLE;
extern CONSTCFGTYPE MAX_Y_TABLE;
extern CONSTCFGTYPE MAX_Z_TABLE;
extern CONSTCFGTYPE MIN_X_TABLE_BASE;
extern CONSTCFGTYPE MIN_Y_TABLE_BASE;
extern CONSTCFGTYPE MIN_Z_TABLE_BASE;
extern CONSTCFGTYPE MAX_X_TABLE_BASE;
extern CONSTCFGTYPE MAX_Y_TABLE_BASE;
extern CONSTCFGTYPE MAX_Z_TABLE_BASE;
extern CONSTCFGTYPE MIN_X_TABLE_NET;
extern CONSTCFGTYPE MIN_Y_TABLE_NET;
extern CONSTCFGTYPE MIN_Z_TABLE_NET;
extern CONSTCFGTYPE MAX_X_TABLE_NET;
extern CONSTCFGTYPE MAX_Y_TABLE_NET;
extern CONSTCFGTYPE MAX_Z_TABLE_NET;
extern CONSTCFGTYPE MIN_X_ROOM;
extern CONSTCFGTYPE MIN_Y_ROOM;
extern CONSTCFGTYPE MIN_Z_ROOM;
extern CONSTCFGTYPE MAX_X_ROOM;
extern CONSTCFGTYPE MAX_Y_ROOM;
extern CONSTCFGTYPE MAX_Z_ROOM;
extern CONSTCFGTYPE MIN_X_STADIUM_BOT;
extern CONSTCFGTYPE MIN_Z_STADIUM_BOT;
extern CONSTCFGTYPE MAX_X_STADIUM_BOT;
extern CONSTCFGTYPE MAX_Z_STADIUM_BOT;
extern CONSTCFGTYPE MIN_X_STADIUM_TOP;
extern CONSTCFGTYPE MIN_Z_STADIUM_TOP;
extern CONSTCFGTYPE MAX_X_STADIUM_TOP;
extern CONSTCFGTYPE MAX_Z_STADIUM_TOP;
extern CONSTCFGTYPE MIN_Y_STADIUM;
extern CONSTCFGTYPE MAX_Y_STADIUM;
extern CONSTCFGTYPE BALL_RADIUS;
extern CONSTCFGTYPE BALL_GRAVITY_ACC;
extern CONSTCFGTYPE BALL_COLLISION_COEEF;
extern CONSTCFGTYPE BALL_FRICTION_COEEF;
extern CONSTCFGTYPE BALL_COLLISION_SPEED;
extern CONSTCFGTYPE BALL_COLLISION_START;
extern CONSTCFGTYPE BALL_SERVE_COEEF;
extern CONSTCFGTYPE BALL_SPEED_MAJOR1;
extern CONSTCFGTYPE BALL_SPEED_MAJOR2;
extern CONSTCFGTYPE BALL_SPEED_MAJOR3;
extern CONSTCFGTYPE BALL_SPEED_MAJOR4;
extern CONSTCFGTYPE BALL_SPEED_MAJOR5;
extern CONSTCFGTYPE BALL_SPEED_MAJOR6;
extern CONSTCFGTYPE BALL_SPEED_MINOR1;
extern CONSTCFGTYPE BALL_SPEED_MINOR2;
extern CONSTCFGTYPE BALL_SPEED_MINOR3;
extern CONSTCFGTYPE BALL_SPEED_MINOR4;
extern CONSTCFGTYPE BALL_SPEED_MINOR5;
extern CONSTCFGTYPE BALL_SPEED_MINOR6;
extern CONSTCFGTYPE BALL_SPIN_FACTOR1;
extern CONSTCFGTYPE BALL_SPIN_FACTOR2;
extern CONSTCFGTYPE BALL_SPIN_FACTOR3;
extern CONSTCFGTYPE BALL_TRAIL_RFACTOR;
extern CONSTCFGTYPE BALL_TRAIL_LENGTH;
extern CONSTCFGTYPE BALL_TRAIL_FLENGTH;
extern CONSTCFGTYPE BALL_SPINEFFECT_WIDTH;
extern CONSTCFGTYPE BALL_SPINEFFECT_HEIGHT;
extern CONSTCFGTYPE HITTIM_DURATION;
extern CONSTCFGTYPE Z_BACK_TOHIT;
extern CONSTCFGTYPE MAX_Z_HITBALL;
extern CONSTCFGTYPE HIT_ACTIONTIME;
extern CONSTCFGTYPE POSTHIT_BACKTIME;
extern CONSTCFGTYPE POSTHIT_BACK_THRESHOLD;
extern CONSTCFGTYPE ACC_THRESHOLD;
extern CONSTCFGTYPE MAX_INTERVALTIME;
extern CONSTCFGTYPE MAX_Z_HITRANGE;
extern CONSTCFGTYPE MIN_Z_HITRANGE;
extern CONSTCFGTYPE STEP_Z;
extern CONSTCFGTYPE MAX_X_HITRANGE;
extern CONSTCFGTYPE MIN_X_HITRANGE;
extern CONSTCFGTYPE STEP_X;
extern CONSTCFGTYPE MAX_Y_HITRANGE;
extern CONSTCFGTYPE MIN_Y_HITRANGE;
extern CONSTCFGTYPE STEP_Y;
extern CONSTCFGTYPE CAMERA_NEAR_VALUE;
extern CONSTCFGTYPE CAMERA_FAR_VALUE;
extern CONSTCFGTYPE REPLAY_POSSIBILITY;
extern CONSTCFGTYPE FILE_LOADINGSCREEN;
extern CONSTCFGTYPE FILE_LOADINGBAR;
extern CONSTCFGTYPE FILE_LOADINGPROGRESS;
extern CONSTCFGTYPE FILE_SETUPINPUT;
extern CONSTCFGTYPE FILE_STARTBAR;
extern CONSTCFGTYPE FILE_DIALOGQUIT;
extern CONSTCFGTYPE FILE_FONT;
extern CONSTCFGTYPE FILE_TEXTURE_SCOREBAR;
extern CONSTCFGTYPE FILE_SCORE_FONT;
extern CONSTCFGTYPE FILE_SCORE_FONT2;
extern CONSTCFGTYPE FILE_BALL_TEXTURE;
extern CONSTCFGTYPE FILE_FLOOR_TEXTURE;
extern CONSTCFGTYPE FILE_RACKET_MESH;
extern CONSTCFGTYPE FILE_RACKET_MESH2;
extern CONSTCFGTYPE FILE_SCENE_MESH;
extern CONSTCFGTYPE FILE_SCENE_TEXTURE;
extern CONSTCFGTYPE FILE_SCENE_MESH_EX;
extern CONSTCFGTYPE FILE_SCENE_TEXTURE_EX;
extern CONSTCFGTYPE FILE_TABLE_MESH;
extern CONSTCFGTYPE FILE_TABLE_TEXTURE;
extern CONSTCFGTYPE FILE_TABLE_NET_MESH;
extern CONSTCFGTYPE FILE_TABLE_NET_TEXTURE;
extern CONSTCFGTYPE FILE_FENCE_TEXTURE;
extern CONSTCFGTYPE FILE_FENCE_TEXTURE_1;
extern CONSTCFGTYPE FILE_FENCE_TEXTURE_2;
extern CONSTCFGTYPE FILE_RACKET_TEXTURE;
extern CONSTCFGTYPE FILE_PLAYER_MESH_1;
extern CONSTCFGTYPE FILE_PLAYER_TEXTURE_1;
extern CONSTCFGTYPE FILE_PLAYER_MESH_2;
extern CONSTCFGTYPE FILE_PLAYER_TEXTURE_2;
extern CONSTCFGTYPE FILE_PLAYER_MESH_3;
extern CONSTCFGTYPE FILE_PLAYER_TEXTURE_3;
extern CONSTCFGTYPE FILE_PLAYER_MESH_4;
extern CONSTCFGTYPE FILE_PLAYER_TEXTURE_4;
extern CONSTCFGTYPE FILE_PLAYER_MESH_5;
extern CONSTCFGTYPE FILE_PLAYER_TEXTURE_5;
extern CONSTCFGTYPE FILE_PLAYER_MESH_6;
extern CONSTCFGTYPE FILE_PLAYER_TEXTURE_6;
extern CONSTCFGTYPE FILE_PLAYER_MESH_7;
extern CONSTCFGTYPE FILE_PLAYER_TEXTURE_7;
extern CONSTCFGTYPE FILE_PLAYER_MESH_8;
extern CONSTCFGTYPE FILE_PLAYER_TEXTURE_8;
extern CONSTCFGTYPE FILE_SOUND_START;
extern CONSTCFGTYPE FILE_SOUND_RAKETKA1;
extern CONSTCFGTYPE FILE_SOUND_RAKETKA2;
extern CONSTCFGTYPE FILE_SOUND_TABLE;
extern CONSTCFGTYPE FILE_SOUND_BEEP;
extern CONSTCFGTYPE FILE_SOUND_APPLAUSE;
extern CONSTCFGTYPE FILE_SOUND_OPENNING;
extern CONSTCFGTYPE FILE_SOUND_END;
extern CONSTCFGTYPE FILE_INTRO_LOGO1;
extern CONSTCFGTYPE FILE_INTRO_LOGO2;
extern CONSTCFGTYPE FILE_MAINMENU_BACKGROUND;
extern CONSTCFGTYPE FILE_MAINMENU_OPTION_START;
extern CONSTCFGTYPE FILE_MAINMENU_OPTION_START_FOCUSED;
extern CONSTCFGTYPE FILE_MAINMENU_OPTION_EXIT;
extern CONSTCFGTYPE FILE_MAINMENU_OPTION_EXIT_FOCUSED;
extern CONSTCFGTYPE FILE_MAINMENU_OPTION_SETUP_DISABLED;
extern CONSTCFGTYPE FILE_MAINMENU_OPTION_REMOTER_DISABLED;
extern CONSTCFGTYPE FILE_MAINMENU_OPTION_ROLE_DISABLED;
extern CONSTCFGTYPE FILE_MAINMENU_OPTION_SINGLE;
extern CONSTCFGTYPE FILE_MAINMENU_OPTION_SINGLE_FOCUSED;
extern CONSTCFGTYPE FILE_MAINMENU_OPTION_DOUBLE;
extern CONSTCFGTYPE FILE_MAINMENU_OPTION_DOUBLE_FOCUSED;
extern CONSTCFGTYPE FILE_MAINMENU_OPTION_NETWORK;
extern CONSTCFGTYPE FILE_MAINMENU_OPTION_NETWORK_FOCUSED;
extern CONSTCFGTYPE FILE_MAINMENU_OPTION_BACK;
extern CONSTCFGTYPE FILE_MAINMENU_OPTION_BACK_FOCUSED;
extern CONSTCFGTYPE FILE_MATCHMENU_BACKGROUND;
extern CONSTCFGTYPE FILE_MATCHMENU_OPTION_CONTINUE;
extern CONSTCFGTYPE FILE_MATCHMENU_OPTION_CONTINUE_FOCUSED;
extern CONSTCFGTYPE FILE_MATCHMENU_OPTION_BACK;
extern CONSTCFGTYPE FILE_MATCHMENU_OPTION_BACK_FOCUSED;
extern CONSTCFGTYPE FILE_REPLAY_1;
extern CONSTCFGTYPE FILE_REPLAY_2;
extern CONSTCFGTYPE FILE_REPLAY_3;
extern CONSTCFGTYPE FILE_REPLAY_4;
extern CONSTCFGTYPE FILE_REPLAY_5;
extern CONSTCFGTYPE FILE_REPLAY_6;
extern CONSTCFGTYPE FILE_LOADINGSCREEN01;
extern CONSTCFGTYPE FILE_LOADINGSCREEN02;
extern CONSTCFGTYPE FILE_LOADINGSCREEN03;
extern CONSTCFGTYPE FILE_LOADINGSCREEN04;
extern CONSTCFGTYPE FILE_LOADINGSCREEN05;
extern CONSTCFGTYPE FILE_LOADINGSCREEN06;
extern CONSTCFGTYPE FILE_LOADINGSCREEN07;
extern CONSTCFGTYPE FILE_LOADINGSCREEN08;
extern CONSTCFGTYPE FILE_MAINMENU_BACKGROUND01;
extern CONSTCFGTYPE FILE_MAINMENU_BACKGROUND02;
extern CONSTCFGTYPE FILE_MAINMENU_BACKGROUND03;
extern CONSTCFGTYPE FILE_MAINMENU_BACKGROUND04;
extern CONSTCFGTYPE FILE_MAINMENU_BACKGROUND05;
extern CONSTCFGTYPE FILE_MAINMENU_BACKGROUND06;
extern CONSTCFGTYPE FILE_MAINMENU_BACKGROUND07;
extern CONSTCFGTYPE FILE_MAINMENU_BACKGROUND08;
extern CONSTCFGTYPE FILE_LOG_DEBUG;
extern CONSTCFGTYPE FILE_RANKLIST_BACKGROUND;
extern CONSTCFGTYPE FILE_DEFAULT_FONT;
extern CONSTCFGTYPE FILE_PLAYER_SELECT_TITLE1;
extern CONSTCFGTYPE FILE_PLAYER_SELECT_TITLE2;
extern CONSTCFGTYPE FILE_PINGPANG_LOGO;
extern CONSTCFGTYPE FILE_PLAYER_SELECT_CONFIRM;
extern CONSTCFGTYPE FILE_PLAYER_SELECT_NAME;
extern CONSTCFGTYPE FILE_PLAYER_SELECT_CHAR_GIRL;
extern CONSTCFGTYPE FILE_PLAYER_SELECT_CHAR_BOY;
extern CONSTCFGTYPE FILE_PLAYER_SELECT_BUTTON_BACK;
extern CONSTCFGTYPE FILE_BALL_SHADOW_TEX;
extern CONSTCFGTYPE FILE_BALL_COLLI_TEX;

extern CONSTCFGTYPE FILE_BALL_SPIN_CW_TEX1;
extern CONSTCFGTYPE FILE_BALL_SPIN_CW_TEX2;
extern CONSTCFGTYPE FILE_BALL_SPIN_CW_TEX3;
extern CONSTCFGTYPE FILE_BALL_SPIN_CW_TEX4;
extern CONSTCFGTYPE FILE_BALL_SPIN_CW_TEX5;
extern CONSTCFGTYPE FILE_BALL_SPIN_CW_TEX6;
extern CONSTCFGTYPE FILE_BALL_SPIN_CW_TEX7;
extern CONSTCFGTYPE FILE_BALL_SPIN_CW_TEX8;

extern CONSTCFGTYPE FILE_BALL_SPIN_CCW_TEX1;
extern CONSTCFGTYPE FILE_BALL_SPIN_CCW_TEX2;
extern CONSTCFGTYPE FILE_BALL_SPIN_CCW_TEX3;
extern CONSTCFGTYPE FILE_BALL_SPIN_CCW_TEX4;
extern CONSTCFGTYPE FILE_BALL_SPIN_CCW_TEX5;
extern CONSTCFGTYPE FILE_BALL_SPIN_CCW_TEX6;
extern CONSTCFGTYPE FILE_BALL_SPIN_CCW_TEX7;
extern CONSTCFGTYPE FILE_BALL_SPIN_CCW_TEX8;

extern CONSTCFGTYPE FILE_BALL_LEFTSHADOW;
extern CONSTCFGTYPE HIT_PREPARE_TIME;

extern CONSTCFGTYPE CFG_LOADING;
extern CONSTCFGTYPE CFG_FILE_CONNECTING;
extern CONSTCFGTYPE CFG_FILE_CONNECT_FAILED_1;
extern CONSTCFGTYPE CFG_FILE_CONNECT_FAILED_2;
extern CONSTCFGTYPE CFG_FILE_CONNECT_SUCCEED;
extern CONSTCFGTYPE CFG_FILE_CONNECT_SQUARE;
extern CONSTCFGTYPE CFG_MAX_CONNECT_TRIES;
extern CONSTCFGTYPE CFG_SECONDS_BEFORE_EXIT;
extern CONSTCFGTYPE CFG_SECONDS_BEFORE_RETRY;

extern CONSTCFGTYPE CFG_ENERGY;
extern CONSTCFGTYPE CFG_ENERGY_MAX_CST;
extern CONSTCFGTYPE CFG_ENERGY_MAX_ACC;
extern CONSTCFGTYPE CFG_ENERGY_FILE_BACKGROUND;
extern CONSTCFGTYPE CFG_ENERGY_FILE_CALORIE;
extern CONSTCFGTYPE CFG_ENERGY_FILE_CONTINUE;

extern CONSTCFGTYPE CFG_FILE_POWER_A;
extern CONSTCFGTYPE CFG_FILE_POWER_B;
extern CONSTCFGTYPE CFG_FILE_POWER_LEVEL;

extern CONSTCFGTYPE CHOP_HIGH2LOW_POSSI;
extern CONSTCFGTYPE SUPERHIT_RATE;
extern CONSTCFGTYPE NPC_SUPERHIT_RATE;
extern CONSTCFGTYPE ACC_HIGH_MODE_THRESHOLD;
extern CONSTCFGTYPE MAX_HIT_COUNT;
extern CONSTCFGTYPE MAX_SUPERHITRATE;
extern CONSTCFGTYPE END_TIME;
extern CONSTCFGTYPE MAX_SUPERHITTIME_FACTOR;
extern CONSTCFGTYPE MIN_SUPERHITTIME_FACTOR;
extern CONSTCFGTYPE MAX_HIT_ACC;
extern CONSTCFGTYPE MAX_CAM_XMOVEOFFSET;
extern CONSTCFGTYPE MIN_CAM_XMOVEOFFSET;
extern CONSTCFGTYPE CAM_ZMOVEOFFSET;
extern CONSTCFGTYPE CAM_ANIM_TIME;

extern CONSTCFGTYPE CFG_FILE_KEYPAD;
extern CONSTCFGTYPE CFG_FILE_KEY_FRAME;
extern CONSTCFGTYPE CFG_FILE_INPUT_ARROW;
extern CONSTCFGTYPE CFG_FILE_INPUT_PLAYER_NAME;

extern CONSTCFGTYPE CFG_FONT_INPUT;
extern CONSTCFGTYPE CFG_FILE_INPUT_HELP;

extern CONSTCFGTYPE CFG_FILE_SPEED_BK;

extern CONSTCFGTYPE MIN_BALL_DISPLAYSPEED;
extern CONSTCFGTYPE MAX_BALL_DISPLAYSPEED;
extern CONSTCFGTYPE SUPERHIT_KEY;
extern CONSTCFGTYPE ACC_SPIN_THRESHOLD_1;
extern CONSTCFGTYPE ACC_SPIN_THRESHOLD_2;
extern CONSTCFGTYPE NPC_SPIN_HITBACK_POSSI;
extern CONSTCFGTYPE SPIN_HITBACK_STRENGTH;

extern CONSTCFGTYPE CFG_GAMELIST;
extern CONSTCFGTYPE CFG_GAMELIST_BK;
extern CONSTCFGTYPE CFG_GAMELIST_ARROW_UP;
extern CONSTCFGTYPE CFG_GAMELIST_ARROW_DOWN;
extern CONSTCFGTYPE CFG_GAMELIST_BUTTON_BACK;
extern CONSTCFGTYPE CFG_GAMELIST_BUTTON_BACK_FOCUSED;
extern CONSTCFGTYPE CFG_GAMELIST_BUTTON_USERLIST;
extern CONSTCFGTYPE CFG_GAMELIST_BUTTON_USERLIST_FOCUSED;
extern CONSTCFGTYPE CFG_GAMELIST_BUTTON_CREATE;
extern CONSTCFGTYPE CFG_GAMELIST_BUTTON_CREATE_FOCUSED;
extern CONSTCFGTYPE CFG_GAMELIST_BUTTON_LIST;
extern CONSTCFGTYPE CFG_GAMELIST_BUTTON_LIST_FOCUSED;
extern CONSTCFGTYPE CFG_GAMELIST_ICON_GAME_SELECTED;
extern CONSTCFGTYPE CFG_GAMELIST_ICON_GAME_WAITING;
extern CONSTCFGTYPE CFG_GAMELIST_ICON_ROOM;

extern CONSTCFGTYPE CFG_USERLIST_BK;
extern CONSTCFGTYPE CFG_USERLIST_ICON_USER_SELECTED;
extern CONSTCFGTYPE CFG_USERLIST_ICON_STATUS_WAITING;
extern CONSTCFGTYPE CFG_USERLIST_ICON_STATUS_PLAYING;
extern CONSTCFGTYPE CFG_USERLIST_ICON_STATUS_IDLE;

extern CONSTCFGTYPE CFG_FILE_NETWORK_WAITING1;
extern CONSTCFGTYPE CFG_FILE_NETWORK_WAITING2;


extern CONSTCFGTYPE CFG_GAME_SERVER_ADDR;
extern CONSTCFGTYPE CFG_GAME_SERVER_PORT;
extern CONSTCFGTYPE CFG_CLIENT_PORT;

extern CONSTCFGTYPE CFG_FILE_LOGIN_FAILED;
extern CONSTCFGTYPE CFG_FILE_SERVER_CONNECTION_FAILED;
extern CONSTCFGTYPE CFG_FILE_NETWORK_DROPPED;
extern CONSTCFGTYPE CFG_FILE_NETWORK_CONNECTING;
extern CONSTCFGTYPE CFG_FILE_NETWORK_RECONNECTING;
extern CONSTCFGTYPE CFG_FILE_GAME_TERMINATED;

extern CONSTCFGTYPE CFG_FILE_DIALOG_BK512x128;

extern CONSTCFGTYPE CFG_DEFAULT_USERNAME;
extern CONSTCFGTYPE CFG_DEFAULT_PASSWORD;

extern CONSTCFGTYPE CFG_FILE_REMOTE_RECONNECTING;
extern CONSTCFGTYPE CFG_FILE_REMOTE_RECONNECT_FAILED;

extern CONSTCFGTYPE CFG_CAMERA_CENTER_Y;
extern CONSTCFGTYPE CFG_CAMERA_VECTOR0_Y;
extern CONSTCFGTYPE CFG_CAMERA_VECTOR3_Y;
extern CONSTCFGTYPE CFG_CAMERA_VECTOR3_Z;
extern CONSTCFGTYPE CFG_CAMERA_DSTVECTOR_X;
extern CONSTCFGTYPE CFG_CAMERA_DSTVECTOR_Y;

extern CONSTCFGTYPE CFG_USERDETAIL;
extern CONSTCFGTYPE FILE_USERDETAIL_BK;
extern CONSTCFGTYPE FILE_USER_OP_INVITE;
extern CONSTCFGTYPE FILE_USER_OP_INVITE_DISABLED;
extern CONSTCFGTYPE FILE_USER_OP_JOIN;
extern CONSTCFGTYPE FILE_USER_OP_JOIN_DISABLED;
extern CONSTCFGTYPE FILE_USER_OP_WATCH;
extern CONSTCFGTYPE FILE_USER_OP_WATCH_DISABLED;
extern CONSTCFGTYPE FILE_USER_OP_BACK;
extern CONSTCFGTYPE FILE_BUTTON_SPRITE;

// Tips texture files
extern CONSTCFGTYPE FILE_TIPS_SERVEBALL1;
extern CONSTCFGTYPE FILE_TIPS_SERVEBALL2;
extern CONSTCFGTYPE FILE_TIPS_SERVEBALL3;

extern CONSTCFGTYPE FILE_TIPS_SWINGBALL1;
extern CONSTCFGTYPE FILE_TIPS_SWINGBALL2;
extern CONSTCFGTYPE FILE_TIPS_SWINGBALL3;

extern CONSTCFGTYPE FILE_TIPS_SPINBALL1;
extern CONSTCFGTYPE FILE_TIPS_SPINBALL2;
extern CONSTCFGTYPE FILE_TIPS_SPINBALL3;

extern CONSTCFGTYPE FILE_TIPS_BUTTON1;
extern CONSTCFGTYPE FILE_TIPS_BUTTON2;
extern CONSTCFGTYPE FILE_TIPS_PLUS;

// File remote lib
extern CONSTCFGTYPE FILE_REMOTE_LIB;
extern CONSTCFGTYPE CFG_USE_WIIMOTE;

#endif //_TEST_SCENE_CFG_H_
